### ISSUE TITLE
Trouble with production server

### ISSUE THREAD

**Issue by ryanbagwell** [jezdez/django-queued-storage#16]
@jezdez, love this app, but I'm having trouble with it on a production server. After uploading a large video (>500MB), it doesn't look like the celery task is ever run.

I confirmed that the [````transfer()````](https://github.com/jezdez/django-queued-storage/blob/develop/queued_storage/backends.py#L189) method in the storage backend is called. I have not be able to confirm that the actual task methods are being called. The Celery log doesn't show any problems or any indication that the task has been queued.

This is only happening on the production server. It works locally using the Django dev server, and it also works for smaller uploads, i.e. 4MB, on both my local pc and production. I'm stumped, and was wondering if you had any ideas about what could be causing the problem. Appreciate any help you could provide.

**Comment by jezdez** [comment]
Full disclosure, I've stopped using this app a while ago and can't help you given personal time constraints. Good luck!
