### ISSUE TITLE
using local file for local access

### ISSUE THREAD

**Issue by jerzyk** [jezdez/django-queued-storage#8]
please, correct me if I'm wrong, but there are no option to specify that for the local file access, file should be accessed locally?

IMHO it will be a great performance improvement (and sometimes can save money) when files that are uploaded to the remote storage wil be accessed locally for the local operations (e.g. generating thumbnails etc.)

please let me know if such an option exists or even if it is planned!

Thanks for this extension!
Janusz

**Comment by ashwoods** [comment]
The default Task doesn't delete the local file, and you can access it directly by using the local storage by hand.
